### ISSUE TITLE
Click the icon used to copy URLs from selected tabs to clipboard, now it opens a menu with stuff, how can I make it like it was before ?

### ISSUE THREAD

**Issue by shodanx2** [igorlogius/copy-taburls#4]
Hi,

This add-on, or maybe another one like it, I don't remember, used to be a one-click affair, you click it and it just copies your selected tabs URL into clipboard with CrLf separating each url, great !

But now when you click it

![image](https://user-images.githubusercontent.com/10621885/206881080-e5ffcce5-3889-4131-8e42-a9fb1ce16af5.png)

It pops out a multiple choice question, which interrupts my flow

![image](https://user-images.githubusercontent.com/10621885/206881091-6bb0a711-142d-417d-aed3-6a61d4822854.png)

I would like to have it work as before, one click and the URLs are in my clipboard !

I might like this multiple choice menu IF it only appeared when I right-clicked on the icon

Maybe you could have a setting where the user can choose which of these function, is the default left-click action

But, me personnally, I want left click to copy URLs and not ask anymore questions !

Thanks

**Comment by igorlogius** [comment]
Yes, it used to work like this, but this behaviour together with the different actions made it very unintuitive to use by inexperienced users, so i opted to make a few changes.  

The toolbar icon popup is now for for "normal" users to use easy but slowly. :) 
And for powerusers with tight workflows you can  assign and use  hotkeys for each action. 

Hope this is a sufficiently good solution for your workflow.

**Comment by igorlogius** [comment]
@shodanx2  
Please let me know if the hotkey solution is working for you so we can either close or expand this issue.  Thanks.

**Comment by shodanx2** [comment]
Hello,

So far the shortcut didn't stick in my mind and when I use this function (not often enough for the keyboard shortcut to stick) I usually go for the buttons on my toolbar

![image](https://user-images.githubusercontent.com/10621885/207154813-3c726903-046f-4a8a-aa20-55668a3b3e11.png)

I have a few suggestions

My prefered solution would be, in this add-on management page, to add an option tab with the option to select the default left-click action. That was experienced user can pick the one they use the most

![image](https://user-images.githubusercontent.com/10621885/207156746-bd1289f7-bc2e-4445-a46f-123b751c65a2.png)

And if possible, it would be great to have all the other options on the right click action, if that's possible ? 

I see there's a firefox provided default right click menu

![image](https://user-images.githubusercontent.com/10621885/207156860-2756bb88-2931-4ea1-a977-aa598be52683.png)


Maybe items could be added to this right click menu ?

I see that some other of my plugins do that

![image](https://user-images.githubusercontent.com/10621885/207156941-dde9f0a8-8642-4b1f-931b-9bcdf76d45ed.png)

![image](https://user-images.githubusercontent.com/10621885/207156985-c202c0af-f435-4d59-a6e2-e44131dde30d.png)

![image](https://user-images.githubusercontent.com/10621885/207157060-00a919c3-644d-4d1e-b041-9af5d5c22cac.png)

![image](https://user-images.githubusercontent.com/10621885/207157161-6acacec7-e5a3-4e90-abc2-7c36416ee236.png)

**Comment by igorlogius** [comment]
Well, i guess i can add a "Single Action" Mode, that when checked, adds the right click menu selection and changes the toolbar icon click action. 

![snip_20221213-022845](https://user-images.githubusercontent.com/67047467/207203864-aade5f7d-ec15-4501-b485-cf9feb4154a4.png)

**Comment by igorlogius** [comment]
feature added to version 1.10.20

**Comment by shodanx2** [comment]
Works great !
I love it !
Thanks !

**Comment by shodanx2** [comment]
Hello,

Sorry to be the bearer of bad news, but it seems something recently broke with the copy url button

It could be an interaction with another add-on however.

Here is what happens.

When I rightclick on the copy url button I can see the menu, I select "copy urls as text" and it appears so on the bottom right notification

However, copy url will still copy urls as link and seems to be stuck at this setting !

![image](https://user-images.githubusercontent.com/10621885/211271807-41bd16bd-331b-49d4-9d1d-4de42dca0576.png)

**Comment by igorlogius** [comment]
@shodanx2 
I'll check. 
Thanks for lettting me know.
