### ISSUE TITLE
Change default keybinds, do NOT use F5, that is the default key for refresh !!

### ISSUE THREAD

**Issue by shodanx2** [igorlogius/copy-taburls#5]
Please change the default keybindings 

F5 should not be used by default by any add-ons

![image](https://user-images.githubusercontent.com/10621885/206884733-34d9e6aa-c900-46e7-9e85-a74ea49b79ae.png)

**Comment by igorlogius** [comment]
I couldn't really think of good default keys ... so the F-keys are only there as placeholders.
Technically i have them not set at all. Maybe that would be better?

**Comment by shodanx2** [comment]
Hello,

I would suggest not binding those shortcuts until you have a found an intuitive shortcut action that does not interfere with firefox's original keyboard bindings.

With that said, I think that 

CTRL+SHIFT+C   would be the ideal shortcut for the "Copy Selected as text"

and CTRL+SHIFT+V would be ideal for the equivalent paste action in your other add-on called "Open Tabs From Clipboard URLs"

Unfortunately, firefox uses these shortcuts for

![image](https://user-images.githubusercontent.com/10621885/207153286-6fd6828d-bfbf-4d23-a3a2-81bf79596741.png)

Personally, I don't use these two shortcuts ever and I would rather use them to copy selected tabs and pasting them into another window.

I would even like to have CTRL+SHIFT+X to cut tabs from a window (in this case it should hide then move to new window, not delete and recreate as copy, so that the loaded data and buffers in those tabs is not lost)

(This key binding is also used by a very obscure function)

![image](https://user-images.githubusercontent.com/10621885/207154178-3e4221b5-946b-4f85-90a6-3c713defca92.png)

I would use these shortcut but unfortunately, I don't know how to unbind some of firefox's default keybindings or if it's even possible ?

**Comment by igorlogius** [comment]
CTRL+SHIFT+C/V ... seems to be used by far to many addons ... which is kind of the reason i did not want to use it as the default. If possible i dont want to get the user into an unexpected situation and i also dont think it is possible at the moment to change/overwrite the built-in keybindings (without much trickery) ... so i guess i'll stick with the function keys for the time being. BUT i will remove the Save Action ... that way only F1 - F4 will be needed. Maybe that helps a little.

**Comment by shodanx2** [comment]
Very well, I think base firefox should have "modify key bindings page" for the user. 
There already is one for all add-ons !
ctrl-shift-c/v makes sense in a lot of situations, the user should get to pick their preferences
I think I will make a bug report on firefox ticker tracker

**Comment by shodanx2** [comment]
Bug report created in firefox bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1805355

Also suggested feature for CTRL+SHIFT+X to copy then hide tabs, matching with feature to open tabs but if hidden tabs are found, move tabs to current window and unhide
